apiVersion: v1
kind: Secret
metadata:
  name: moneyhero-backend-secret
  namespace: moneyhero
type: Opaque
stringData:
  SUPABASE_URL: "https://gmyfrjymfmsjxwnxyjes.supabase.co"
  SUPABASE_SERVICE_ROLE_KEY: "https://gmyfrjymfmsjxwnxyjes.supabase.co"
  JWT_SECRET: "hola123"