apiVersion: v1
kind: Secret
metadata:
  name: moneyhero-backend-secret
  namespace: moneyhero
type: Opaque
stringData:
  SUPABASE_URL: "https://gmyfrjymfmsjxwnxyjes.supabase.co"
  SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdteWZyanltZm1zanh3bnh5amVzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTM3OTY2NCwiZXhwIjoyMDk2OTU1NjY0fQ.bAB8i7FO0u9yD6SIxcqGya9ynCOroQhfyjciZETRhag"
  JWT_SECRET: "hola123"