apiVersion: v1
kind: Service
metadata:
  name: moneyhero-frontend-service
  namespace: moneyhero
spec:
  type: NodePort
  selector:
    app: moneyhero-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30083